Organizations:
    - &${ORG}
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ${ORG}MSP

        # ID to load the MSP definition as
        ID: ${ORG}MSP

        MSPDir: ${PEER_BASE}/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('${ORG}MSP.admin', '${ORG}MSP.peer', '${ORG}MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('${ORG}MSP.admin', '${ORG}MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('${ORG}MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('${ORG}MSP.peer')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.${HOSTNAME}.${DOMAIN}
              Port: ${PORT}
