#!/bin/sh
sleep 5;

MY_IP=$(hostname -i)

export CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=${MY_IP}:5984
export CORE_PEER_LISTENADDRESS=${MY_IP}:7058
#export CORE_PEER_CHAINCODELISTENADDRESS=${MY_IP}:7052
#export CORE_VM_ENDPOINT=tcp://${MY_IP}:2375

peer node start
