apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: blockchain-adapter-${HOSTNAME}
  name: blockchain-adapter-${HOSTNAME}
  namespace: ${KUBENS}
spec:
# enable external access
#  externalTrafficPolicy: Cluster
#  externalIPs:
#  - MYHOSTIP
#  type: NodePort
  ports:
  - name: "blockchain-adapter-${HOSTNAME}"
    port: ${BLOCKCHAIN_ADAPTER_PORT}
    targetPort: ${BLOCKCHAIN_ADAPTER_PORT}
  selector:
    io.kompose.service: blockchain-adapter-${HOSTNAME}
