apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: offchain-db-${HOSTNAME}
  name: offchain-db-${HOSTNAME}
  namespace: ${KUBENS}
spec:
# enable external access
#  externalTrafficPolicy: Cluster
#  externalIPs:
#  - MYHOSTIP
#  type: NodePort
  ports:
  - name: "offchain-db-${HOSTNAME}"
    port: ${MYSQL_SERVER_PORT}
    targetPort: ${MYSQL_SERVER_PORT}
  selector:
    io.kompose.service: offchain-db-${HOSTNAME}
