#!/bin/bash

export CORE_PEER_LOCALMSPID=${ORG}MSP
export CORE_PEER_TLS_ENABLED=true
export CORE_PEER_TLS_CLIENTAUTHREQUIRED=true

export CORE_PEER_ADDRESS=${PEER_NAME}.${HOSTNAME}.${DOMAIN}:${PEER_PORT}

export CORE_PEER_TLS_CLIENTKEY_FILE=${ADMIN_BASE}/tls/server.key
export CORE_PEER_TLS_CLIENTCERT_FILE=${ADMIN_BASE}/tls/server.crt
export CORE_PEER_TLS_ROOTCERT_FILE=${ADMIN_BASE}/tls/ca.crt
export CORE_PEER_MSP_CLIENTKEY_FILE=${ADMIN_BASE}/msp/keystore/priv_sk
export CORE_PEER_MSP_CLIENTCERT_FILE=${ADMIN_BASE}/msp/signcerts/Admin@${HOSTNAME}.${DOMAIN}-cert.pem
export CORE_PEER_MSP_ROOTCERT_FILE=${PEER_BASE}/tls/ca.crt


discover peers  --tlsKey=$CORE_PEER_TLS_CLIENTKEY_FILE --tlsCert=$CORE_PEER_TLS_CLIENTCERT_FILE --peerTLSCA=$CORE_PEER_TLS_ROOTCERT_FILE \
 --MSP=$CORE_PEER_LOCALMSPID --userKey $CORE_PEER_MSP_CLIENTKEY_FILE --userCert $CORE_PEER_MSP_CLIENTCERT_FILE --server ${PEER_NAME}.${HOSTNAME}.${DOMAIN}:${PEER_PORT} --channel ${CHANNEL_NAME}

exit $?
