apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  annotations:
  labels:
    k8s-app: offchain-db-adapter-${HOSTNAME}
    io.kompose.service: offchain-db-adapter-${HOSTNAME}
  name: offchain-db-adapter
  namespace: ${KUBENS}
spec:
  selector:
    matchLabels:
      app: offchain-db-adapter-${HOSTNAME}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app: offchain-db-adapter-${HOSTNAME}
        #io.kompose.network/kubefile_gsmawr_msp: "true"
        #io.kompose.service: offchain-db-addapter-${HOSTNAME}
        io.kompose.service: offchain-db-adapter-${HOSTNAME}
    spec:
      containers:
      - image: gcr.io/roamingonblockchain/offchain-db-adapter:0.1
        name: offchain-db-adapter-${HOSTNAME}
        env:
        - name: ODBA_MYSQL_SERVER_HOST
          value: offchain-db-${HOSTNAME}
        - name: ODBA_MYSQL_SERVER_PORT
          value: "${MYSQL_SERVER_PORT}"
        - name: ODBA_MYSQL_USER
          value:  ${OFFCHAIN_MYSQL_USER}
        - name: ODBA_MYSQL_PASSWORD
          value: ${OFFCHAIN_MYSQL_PASSWORD}
        - name: ODBA_MYSQL_DATABASE
          value: ${OFFCHAIN_MYSQL_DB}
        - name: ODBA_REST_PORT
          value: "${OFFCHAIN_REST_PORT}"
        ports:
        - containerPort: ${OFFCHAIN_REST_PORT}
          name: odbap-${HOSTNAME}
      imagePullSecrets:
      - name: nomad-secret
      hostname: offchain-db-adapter-${HOSTNAME}
      dnsPolicy: ClusterFirst
      restartPolicy: Always