apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: offchain-db-adapter-${HOSTNAME}
  name: offchain-db-adapter-${HOSTNAME}
  namespace: ${KUBENS}
spec:
# enable external access
#  externalTrafficPolicy: Cluster
#  externalIPs:
#  - MYHOSTIP
#  type: NodePort
  ports:
  - name: "odbap-${HOSTNAME}"
    port: ${OFFCHAIN_REST_PORT}
    targetPort: ${OFFCHAIN_REST_PORT}
  selector:
    io.kompose.service: offchain-db-adapter-${HOSTNAME}
