apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: ca-${MYHOST}
  name: ca-${MYHOST}
  namespace: ${KUBENS}
spec:
# enable external access
#  externalTrafficPolicy: Cluster
#  externalIPs:
#  - MYHOSTIP
#  type: NodePort
  ports:
  - name: "ca-${MYHOST}"
    port: ${CA_PORT}
    targetPort: ${CA_PORT}
#    nodePort: 30754
  selector:
    io.kompose.service: ca-${MYHOST}

