apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  annotations:
  labels:
    k8s-app: calculator-${HOSTNAME}
    io.kompose.service: calculator-${HOSTNAME}
  name: calculator
  namespace: ${KUBENS}
spec:
  selector:
    matchLabels:
      app: calculator-${HOSTNAME}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
#        io.kompose.network/kubefile_gsmawr_msp: "true"
        io.kompose.service: calculator-${HOSTNAME}
        app: calculator-${HOSTNAME}
    spec:
      containers:
      - image: gcr.io/roamingonblockchain/calculator:0.4.4
        name: calculator-${HOSTNAME}
        ports:
        - containerPort: 8080
          name: calculator
      imagePullSecrets:
      - name: nomad-secret
      hostname: calculator-${HOSTNAME}
      dnsPolicy: ClusterFirst
      restartPolicy: Always