apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: chaincode-${HOSTNAME}
  name: chaincode-${HOSTNAME}
  namespace: ${KUBENS}
spec:
# enable external access
#  externalTrafficPolicy: Cluster
#  externalIPs:
#  - MYHOSTIP
#  type: NodePort
  ports:
  - name: "chaincode-${HOSTNAME}"
    port: ${CHAINCODE_PORT}
    targetPort: 7052
  selector:
    io.kompose.service: chaincode-${HOSTNAME}
