apiVersion: v1
kind: Pod
metadata:
  name: fabric-tools
  namespace: ${KUBENS}
spec:
  volumes:
  - name: data-mount
    persistentVolumeClaim:
      claimName: data-claim
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  containers:
    - name: fabric-tools
      image: ${IMAGE_FABRIC_TOOLS}
      imagePullPolicy: Always
      command: ["sh", "-c", "sleep 48h"]
      envFrom:
        - configMapRef:
            name: proxy-environment-variables
      env:
      - name: TZ
        value: "UTC"
      - name: ORG
        value: ${HOSTNAME}
      - name: PORT
        value: "${PEER_PORT}"
      - name: PEER
        value: ${PEER_NAME}
      - name: GOPATH
        value: /opt/gopath
      - name: CORE_VM_ENDPOINT
        value: unix:///host/var/run/docker.sock
      - name: FABRIC_LOGGING_SPEC
        value: INFO
      - name: CORE_PEER_ID
        value: cli-${HOSTNAME}
      - name: CORE_PEER_ADDRESS
        value: ${PEER_NAME}.${HOSTNAME}.${DOMAIN}:${PEER_PORT}
      - name: CORE_PEER_LOCALMSPID
        value: ${ORG}
      - name: CORE_PEER_MSPCONFIGPATH
        value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${HOSTNAME}.${DOMAIN}/users/Admin@${HOSTNAME}.${DOMAIN}/msp
      - name: CORE_PEER_TLS_ENABLED
        value: "true"
      - name: CORE_PEER_TLS_CERT_FILE
        value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${HOSTNAME}.${DOMAIN}/peers/${PEER_NAME}.${HOSTNAME}.${DOMAIN}/tls/server.crt
      - name: CORE_PEER_TLS_KEY_FILE
        value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${HOSTNAME}.${DOMAIN}/peers/${PEER_NAME}.${HOSTNAME}.${DOMAIN}/tls/server.key
      - name: CORE_PEER_TLS_ROOTCERT_FILE
        value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${HOSTNAME}.${DOMAIN}/peers/${PEER_NAME}.${HOSTNAME}.${DOMAIN}/tls/ca.crt
      - name: CORE_PEER_TLS_CLIENTAUTHREQUIRED
        value: "true"
      - name: CORE_PEER_TLS_CLIENTCERT_FILE
        value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${HOSTNAME}.${DOMAIN}/users/Admin@${HOSTNAME}.${DOMAIN}/tls/client.crt
      - name: CORE_PEER_TLS_CLIENTKEY_FILE
        value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${HOSTNAME}.${DOMAIN}/users/Admin@${HOSTNAME}.${DOMAIN}/tls/client.key
      #workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      volumeMounts:
        - mountPath: ${PV_PATH}
          name: data-mount
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
        - name: data-mount #data-pvc
          subPath: chaincode
          mountPath: /opt/gopath/src/github.com/chaincode
        - name: data-mount #data-pvc
          subPath: crypto-config
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
        - name: data-mount #data-pvc
          subPath: channel-artifacts
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts 
        - name: data-mount #data-pvc
          subPath: organizations
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/cli  