apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: common-adapter-${HOSTNAME}
  name: common-adapter-${HOSTNAME}
  namespace: ${KUBENS}
spec:
# enable external access
#  externalTrafficPolicy: Cluster
#  externalIPs:
#  - ${PEER_EXTERNAL_IP}
#  type: NodePort
  ports:
  - name: "common-adapter-${HOSTNAME}"
    port: ${COMMON_ADAPTER_PORT}
    targetPort: 3000
  selector:
    io.kompose.service: common-adapter-${HOSTNAME}
---    
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: common-adapter-${HOSTNAME}
  name: common-adapter-db-${HOSTNAME}
  namespace: ${KUBENS}
spec:
# enable external access
#  externalTrafficPolicy: Cluster
#  externalIPs:
#  - ${PEER_EXTERNAL_IP}
#  type: NodePort
  ports:
  - name: "common-adapter-db-${HOSTNAME}"
    port: ${COMMON_ADAPTER_MONGO_PORT}
    targetPort: 27017
  selector:
    io.kompose.service: common-adapter-${HOSTNAME}
    
