apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume 
  namespace: ${KUBENS}
  labels:
    type: local
spec:
  storageClassName: ${PV_STORAGE_CLASS}
  capacity:
    storage: ${PV_SIZE}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "${PV_PATH}${MYHOST}-pv-volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-claim
  namespace: ${KUBENS}
spec:
  storageClassName: ${PV_STORAGE_CLASS}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${PV_SIZE}
