apiVersion: v1
kind: Pod
metadata:
  name: fabric-tools
  namespace: ${KUBENS}
spec:
  volumes:
  - name: data-mount
    persistentVolumeClaim:
      claimName: data-claim
  containers:
    - name: fabric-tools
      image: ${IMAGE_FABRIC_TOOLS}
      imagePullPolicy: Always
      command: ["sh", "-c", "sleep infinity"]
      envFrom:
        - configMapRef:
            name: proxy-environment-variables
      env:
      - name: TZ
        value: "UTC"
      volumeMounts:
        - mountPath: ${PV_PATH}
          name: data-mount
