apiVersion: v1
kind: Pod
metadata:
  name: fabric-tools
  namespace: ${KUBENS}
spec:
  volumes:
  - name: data-mount
    persistentVolumeClaim:
      claimName: data-claim
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  containers:
    - name: fabrictools
      image: hyperledger/fabric-tools:amd64-1.3.0
      imagePullPolicy: Always
      command: ["sh", "-c", "sleep 48h"]
      env:
      - name: TZ
        value: "UTC"
      volumeMounts:
        - mountPath: ${PV_PATH}
          name: data-mount
        - mountPath: /host/var/run/docker.sock
          name: dockersocket