apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
#    io.kompose.network/kubefile-gsmawr-msp: "true"
    io.kompose.service: ${PEER_NAME}-${MYHOST}
  name: ${PEER_NAME}-${MYHOST}
  namespace: ${KUBENS}
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: ${PEER_NAME}
  template:
    metadata:
      labels:
       app: ${PEER_NAME}
    spec:
      containers:
      - name: couchdb
        image: ${IMAGE_COUCHDB}
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: proxy-environment-variables
        env:
        - name: COUCHDB_USER
          value: dbadmin
        - name: COUCHDB_PASSWORD
          value: dbadminpw
        ports:
        - containerPort: 5984
          protocol: TCP
        volumeMounts:
        - name: data-pvc
          subPath: hyperledger-db
          mountPath: /opt/couchdb/data

      - name: peer
        image: ${IMAGE_FABRIC_PEER}
        imagePullPolicy: IfNotPresent
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: [ "/opt/gopath/src/github.com/hyperledger/fabric/peer/peer_start.sh" ]
        envFrom:
          - configMapRef:
              name: proxy-environment-variables
        env:
        - name: CORE_OPERATIONS_LISTENADDRESS
          value: 0.0.0.0:8088
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: CouchDB
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: localhost:5984
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
          value: dbadmin
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
          value: dbadminpw
        - name: CORE_PEER_ADDRESS
          value: 0.0.0.0:${PEER_PORT}
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:${PEER_PORT}
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: ${PEER_NAME}.${HOSTNAME}.${DOMAIN}:${PEER_PORT}
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: ${PEER_NAME}.${HOSTNAME}.${DOMAIN}:${PEER_PORT}
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_ID
          value: ${PEER_NAME}.${HOSTNAME}.${DOMAIN}
        - name: CORE_PEER_LOCALMSPID
          value: ${ORG}MSP
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /etc/hyperledger/fabric/tls/ca.crt
        - name: CORE_PEER_TLS_CERT_FILE
          value: /etc/hyperledger/fabric/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /etc/hyperledger/fabric/tls/server.key
        - name: CORE_PEER_TLS_CLIENTAUTHREQUIRED
          value: "true"
        - name: CORE_PEER_TLS_CLIENTROOTCAS_FILES
          value: /etc/hyperledger/fabric/tls/ca.crt
        - name: CORE_PEER_TLS_CLIENTCERT_FILE
          value: /etc/hyperledger/fabric/tls/server.crt
        - name: CORE_PEER_TLS_CLIENTKEY_FILE
          value: /etc/hyperledger/fabric/tls/server.key
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "false"
        - name: CORE_VM_ENDPOINT
          value: tcp://0.0.0.0:2375
        - name: FABRIC_LOGGING_SPEC
          value: INFO
        - name: CORE_PEER_GOSSIP_PVTDATA_PULLRETRYTHRESHOLD
          value: 3s
        - name: CORE_PEER_GOSSIP_PVTDATA_RECONCILESLEEPINTERVAL
          value: 5m
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8088
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: ${PEER_PORT}
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/hyperledger/fabric/msp
          name: data-pvc
          subPath: peer/peers/${PEER_NAME}.${HOSTNAME}.${DOMAIN}/msp
        - mountPath: /etc/hyperledger/fabric/tls
          name: data-pvc
          subPath: peer/peers/${PEER_NAME}.${HOSTNAME}.${DOMAIN}/tls
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer
          name: data-pvc
          subPath: peer/home/
        - mountPath: /var/hyperledger/production
          name: data-pvc
          subPath: peer/production/
        - mountPath: /builders/external
          name: data-pvc
          subPath: peer/builders/
        - mountPath: /etc/hyperledger/fabric/core.yaml
          name: data-pvc
          subPath: peer/core.yaml
      - name: dind
        image: ${IMAGE_DIND}
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: proxy-environment-variables        
        ports:
        - containerPort: 2375
          protocol: TCP
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true


      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      hostname: ${PEER_NAME}-${MYHOST}
      restartPolicy: Always
      volumes:
      - name: data-pvc
        persistentVolumeClaim:
          claimName: data-claim