apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: ${PEER_NAME}
  name: ${PEER_NAME}
  namespace: ${KUBENS}
spec:
  externalTrafficPolicy: Cluster
  externalIPs:
  - ${PEER_EXTERNAL_IP}
  type: NodePort
  ports:
  - name: "default"
    port: ${PEER_PORT}
    protocol: TCP
    targetPort: ${PEER_PORT}
    nodePort: 30758
  selector:
    io.kompose.service: ${PEER_NAME}
  sessionAffinity: None

