apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-webapp-${HOSTNAME}
  namespace: ${KUBENS}
  labels:
    app: nginx-svc-webapp-${HOSTNAME}
spec:
  externalTrafficPolicy: Cluster
  externalIPs:
  - ${PEER_EXTERNAL_IP}
  type: NodePort
  ports:
  - port: ${NGINX_HTTPS_PORT}
    protocol: TCP
    name: https
    targetPort: ${NGINX_HTTP2_PORT}
    nodePort: ${NGINX_NODE_PORT}
#  - port: ${NGINX_HTTP_PORT}
#    protocol: TCP
#    name: http
#    targetPort: ${NGINX_HTTP_PORT}
#    nodePort: ${NGINX_CERT_NODE_PORT}
  selector:
    app: nginx-webapp-${HOSTNAME}
  sessionAffinity: None
