apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: webapp-${HOSTNAME}
  name: webapp-${HOSTNAME}
  namespace: ${KUBENS}
spec:
# enable external access
#  externalTrafficPolicy: Cluster
#  externalIPs:
#  - MYHOSTIP
#  type: NodePort
  ports:
  - name: "webapp-${HOSTNAME}"
    port: ${WEBAPP_PORT}
    targetPort: ${WEBAPP_PORT}
  selector:
    app: webapp-${HOSTNAME}

