apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-certbot-${HOSTNAME}
  namespace: ${KUBENS}
  labels:
    app: nginx-svc-certbot-${HOSTNAME}
spec:
  externalTrafficPolicy: Cluster
  externalIPs:
  - ${PEER_EXTERNAL_IP}
  type: NodePort
  ports:
  - port: ${NGINX_HTTP_PORT}
    protocol: TCP
    name: http
    targetPort: ${NGINX_HTTP_PORT}
    nodePort: ${NGINX_CERT_NODE_PORT}
  selector:
    app: nginx-certbot-${HOSTNAME}
  sessionAffinity: None
